added startup check and additional option + docs
augensalat/mojolicious-plugin-sizelimit pull request #6
Opened 2020-05-28 04:29 UTC by wsdookadr

The following Perl program was written. The `max_memory_size` will intentionally not be met in order to trigger the shut down of the process.

```perl
#!/usr/bin/perl
use lib qw(lib);
use Mojolicious::Lite;
use Mojolicious::Plugin::SizeLimit;
plugin 'Mojolicious::Plugin::SizeLimit', 
    { 
        max_process_size => (1024**2) * 0.01,
        startup_check    => 1,
    };
get '/' => sub {
  my $c = shift;
};
app->start;
```

Fixes #2

2020-05-28 08:01 UTC, augensalat requested changes
Hi, thanks again.
Unfortunately this is a total "doing-it-wrong".
1. You must never `exit` the Mojolicious process! You find the correct way for process termination in the original code in line 71.
2. You are doubling code. All check-code is already there. The challenge is to run the `_limits_are_exceeded` function at start, and change this function that if might be given a `$count` argument of `0` or `undef`, which then must be handled in a sensible way.

2020-05-29 05:01 UTC, wsdookadr commented
> Unfortunately this is a total "doing-it-wrong".
Yes, that is true, it was completely wrong.
> You must never exit the Mojolicious process!
Yup, I'm using `stop_gracefully` now
> You are doubling code [..] The challenge is to run the _limits_are_exceeded function at start, and change this function
Yes, I've completely the functions  `_make_limits_are_exceeded` and `_make_count_requests`, and added docs for them. I've also added a test for `startup_check`.

If #5 is merged first, and then this one #6 , then all tests will pass.

2020-05-29 11:43 UTC, wsdookadr commented
> I will have a look at the problem later or in the next days.

Hi @augensalat 

Is anything else needed here? Can I help you with anything for this pull request to get merged?

2020-05-29 12:03 UTC, wsdookadr commented
Closing due to maintainer being unresponsive

2020-05-29 12:03 UTC, closed without merging